version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
    - /bin/bash
    - -c
    - |
      sleep infinity
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    stdin_open: true
    tty: true
